spring:
    appContextType: web

    configLocationsType: classpath

    configLocations:
       - dropwizard-service.xml
       
    resources:
       - loadWebServiceController
       - calcREST

http:
  port: 9091
  adminPort: 8083